### ISSUE TITLE
Analysis - message and auto-reload when annotation version is out of date

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#107]
DL Jun 2020: When you upgrade annotation versions, we often delete the old ones.

If the AV for an analysis is out of date, we should show a message and allow people to set to latest version and reload.

This means we can avoid recalculating all the analyses, and just do it on demand.

**Comment by sksmi** [comment]
Transferred from VG 2657.

**Comment by davmlaw** [comment]
* If the analysis version is not valid, will show errors in nodes, and in analysis settings
* Will show warning in analysis settings about being out of date
* If any errors or warnings, will open analysis settings upon loading analysis so you can see them

**Comment by sksmi** [comment]
Tested on both GRCh37 & GRCh38 analyses. 

Following completed no errors:
- No messaging on opening new analysis
- Error & warning on use of invalid & outdated annotation (analysis settings & node), grids not available.
- Error & warning also present in analysis settings in analysis grid. 
- Error & warning removed after updating annotation version.

Errors generated in analysis when trying to view nodes:
[#2305](https://rollbar.com/jimmy.andrews/VariantGrid/items/2305/?utm_campaign=occurrence_message&utm_medium=slack&utm_source=rollbar-notification) 
[#2306 ](https://rollbar.com/jimmy.andrews/VariantGrid/items/2306/?utm_campaign=occurrence_message&utm_medium=slack&utm_source=rollbar-notification)
505 (see [slack](https://variantgrid.slack.com/archives/G01CD8FEH09/p1613687526003000)) 

Minor suggestion: 
For error message: Analysis: AnnotationVersion: 11 (2020-09-04) missing sub annotations: gene_annotation_version
Fix this inAnalysis settings

could we replace 'Fix this in Analysis Settings' to 'Error due to outdated annotation version. To fix, update annotation version in Analysis Settings and force reload analysis.'

Added to test case: [VG-132](https://app.qase.io/case/VG/edit/132).

**Comment by davmlaw** [comment]
No we can't really fix this warning to be better.

"Error due to outdated annotation version. To fix, update annotation version in Analysis Settings and force reload analysis.'" - this is the problem and solution for this analysis on this server, not a general identification of problem and solution (it's too much work now for marginal benefit to fully detect what went wrong)

The error shown here has to work on the:

* Node
* Analysis settings

I added a small link at the back to send people to the right place When you are directed to the analysis settings page, we do give you more info about being out of date and a new one being available.

**Comment by sksmi** [comment]
Sounds good. Closing as tested above.
