### ISSUE TITLE
View upload processing page needs a few things added back

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#1097]
Grid needs to have start/end columns added back - really need this to work out what was run when

**Profile-like summary at the top**

This was useful to work out where the time was going

![Screenshot from 2024-06-24 16-28-20](https://github.com/SACGF/variantgrid/assets/763201/54de551d-925b-443d-99ba-ebc7acef0598)

**Comment by TheMadBug** [comment]
@davmlaw 

So we have that table that you pasted a screenshot of now only when a single step has been run multiple times, otherwise it's just redundant to the normal table.

The normal table can have its rows expanded to see the start/end times
<img width="1132" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMENMQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--439b827b14c0c04ed2e8508a155bb275b2a2c90c/CleanShot%202024-06-25%20at%2013.46.07.jpg" alt="CleanShot 2024-06-25 at 13.46.07.jpg" />

Do we just need to move start time back as a table column?

**Comment by davmlaw** [comment]
Yeah just add the start/end (sortable) to the bottom table

For profiling - this is very low priority and am happy to hide it by default because I only need it rarely, but what I am after is "cumulative time" - ie how long a step runs in total, so that I know what to prioritize when optimising an import

**Comment by TheMadBug** [comment]
I've added `start_date` to the table view of individual steps and made it render the seconds.
Since we have `start_date` and duration I feel adding `end_date` to the table doesn't add much information.

I've also rendered all the times properly so it will be in the timezone of the browser as well as in more programmer format of yyyy-mm-dd hh:mm:ss.

Re the cumulative time, see https://test.shariant.org.au/upload/view_upload_pipeline/9138 here's an example of it being used. The toggle only appears at all if there is at least one step that's occurred multiple times (as otherwise the whole ting is redundant to All Upload Steps).
That said, if the table is present, it should probably be expanded by default - I'll make that change.

Lastly the UploadPipeline admin page is a little more useful now that it has a search for the pipeline name if you ever wanted to filter from there (when you drill in there'll be a link to View on Site).

**Comment by davmlaw** [comment]
I like sorting by start/end date to know what was run when. The reason I use this table is when a pipeline crashed out and I'm trying to debug why

**Comment by TheMadBug** [comment]
I don't really see what sorting by end date will pick up that sorting by start don't wont - but I mean, you are the main user of that page, so if you want end date back - sure.

On that note would it be more useful if start/end listed miliseconds too?

**Comment by TheMadBug** [comment]
I've added end date as well as milliseconds to the table.

(I need to do a little bit of work to consolodate rendering of date/time/millisecond across tables on web pages - but don't want to muck around with it until after this build)

**Comment by TheMadBug** [comment]
Dave to close this task if he feels there's enough info there now.

**Comment by davmlaw** [comment]
Another thing I miss is being able to quickly scan the grid and find an input/output file - so I can copy/paste it in the shell and quickly see where the process went wrong

**Comment by davmlaw** [comment]
> what sorting by end date will pick up that sorting by start don't wont 

Some jobs can start before others and end later

**Comment by davmlaw** [comment]
Will do this and fix [rollbar issue](https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/5168?utm_campaign=occurrence_message)

```
render_cell(/opt/variantgrid/snpdb/views/datatable_view.py:377)

return column.renderer(render_data)

-
at
render_duration(/opt/variantgrid/upload/grids.py:28)
    delta = end_date - row["start_date"]
```

**Comment by davmlaw** [comment]
Added columns (and made is scroll in X if too big)

removed JQGrid
