### ISSUE TITLE
ClinGenKB links to incorrect gene

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#113]
**Describe the bug**
ClinGenKB links to HOMER gene instead of GATA2.

**To Reproduce**
Steps to reproduce the behavior including URLs. e.g.
1. Go to https://variantgrid.com/classification/classification/1575
2. Click on 'ClinGenKB' link (in light grey)
3. Takes you to https://search.clinicalgenome.org/kb/genes/HGNC:17513 (HOMER), should take you to https://search.clinicalgenome.org/kb/genes/HGNC:4171 (GATA2)

**Comment by davmlaw** [comment]
> ClinGenKB links to HOMER gene

D'oh

**Comment by TheMadBug** [comment]
Links in light grey are like that because they are missing key bits of information.
The tooltip for ClinGenKB on that form says "Missing HGNC ID".
Looking through the change log hgnc_id was never provided.
So the link was taking you to just "https://search.clinicalgenome.org/"
*BUT*
It turns out going to that URL randomly redirects to a gene, maybe something in your cookie history, for me it redirects to https://search.clinicalgenome.org/kb/genes/HGNC:25068

So I need a better "You're missing data" URL due to that super strange behaviour.
https://search.clinicalgenome.org/kb/home?term= looks like a better option.
In theory I could put the Gene Symbol in there - though I like the distinction of "our annotations said this was the exact HGNC ID" vs "something went a little wrong, here's the search page, best if you find the exact one yourself".

So for now I'll just make `https://search.clinicalgenome.org/kb/home?term=` the default URL.

**Comment by TheMadBug** [comment]
I've now made it so both clinicalgenome and monarch have a HGNC ID link that then falls back on a Gene Symbol link, that then falls back on a good default search page.

**Comment by EmmaTudini** [comment]
Testing:
- Logged into Shariant test as non-admin assigned to VCGS (emmatudini@gmail.com)
- Git Hash
60523306b32b5f99e160e5f50e8f8aa22eb8466e
All for variant - NM_000546.5:c.1149C>T
- Record 1 - HGNC ID, no gene symbol
- Record 2 - gene symbol from chgvs, no HGNC ID
- Record 3 - gene symbol from field, no HGNC ID
- Record 4 - gene symbol from field and HGNC ID
- Record 5 - gene symbol from field and conflicting HGNC ID
- Record 6 - HGNC ID and gene symbol from transcript
- Record 7 - no HGNC ID or gene symbol

Expected output:
If HGNC ID present, use that to create valid links to HGNC ID in clingen and monarch. If gene symbol provided in chgvs or gene symbol, then use that to create valid links. If conflict, choose HGNC ID. If neither, link to general search page.

Actual output: Passed

Note: @TheMadBug When providing a HGNC ID, the user is taken to specific gene page (e.g. https://search.clinicalgenome.org/kb/genes/HGNC:11998  and https://monarchinitiative.org/gene/HGNC:11998). If gene symbol only provided, it goes to a link to search for the gene name - https://search.clinicalgenome.org/kb/home?term=TP53 and https://monarchinitiative.org/search/TP53. Assume that this is because you can't directly input the gene name into the HGNC links?

**Comment by TheMadBug** [comment]
Correct, you can see from the monarch initiative for example there's somewhere around 10 different TP53 (depending on what taxonomy you're talking about) and sadly the page doesn't let us provide taxonomy as part of the search criteria.
