### ISSUE TITLE
MANE - Assignment of canonical transcript

### ISSUE THREAD

**Issue by EmmaTudini** [SACGF/variantgrid#13]
Currently in Shariant, one of the reasons for not displaying the hotspot graph is that I believe we're not calculating the canonical transcript properly.

For example, If I created a new classification for BRCA1 in GRCh37 - the canonical transcript provided is NM_007300.4. If I create it in GRCh38, the canonical transcript is NR_027676.2. Neither of these transcripts are correct. 

I uploaded 17:43063930 C>T (a BRCA1 variant) to the VEP web portal in GRCh37 and GRCh37. For GRCh37 - under canonical it gave NM_007300.4 as above. This is just the longest transcript - not the refseq select or MANE transcript (and I think we should be working off those to replicate Clinvar's stance). For GRCh38 - it was unable to provide any NM transcript (only ENST) but did show that the MANE transcript was NM_007294.4. I think this may be why the canonical transcript is defaulting to an NR_ in Shariant

So in light of all of this - i don't think VEP is a reliable source to pull canonical transcripts from (unless we decide to go with using the MANE transcripts).

There are two other refseq specific places to get the canonical transcript:

1. "Refseq select". See: https://www.ncbi.nlm.nih.gov/refseq/refseq_select/#Picking for more info on how they pick a transcript. Unlike Ensembl which defaults to the longest transcript (curators don't believe in this), they are manually curated. See flowchart below:

![Screen Shot 2020-09-09 at 2.31.05 pm.png](https://images.zenhubusercontent.com/5b9760d2e008eb0aea5fff6c/f53e21ac-5b3d-4b40-8b36-80ead11cacab)

It looks like you can get a download for GRCh38 from here: https://ftp.ncbi.nlm.nih.gov/genomes/refseq/vertebrate_mammalian/Homo_sapiens/annotation_releases/current/

2. The MANE consortium now annotates the matching transcript between ENST and Refseq for 80% coding genes across the genome in GRCh38. 
"The goal of this project is to provide a minimal set of matching RefSeq and Ensembl transcripts of human protein-coding genes, where the transcripts from a matched pair are identical (5’ UTR, coding region and 3’ UTR), but retain their respective identifiers."
See: https://www.ncbi.nlm.nih.gov/refseq/MANE/

It sounds like most of the time the refseq select and the MANE select align, but I don't think we can assume that this happens 100% of the time. It also looks like MANE select is becoming the preferred transcript - e.g. on the refseq select website - it says that MANE select can sometimes be displayed instead of Refseq select. 

MANE select data is located here: https://ftp.ncbi.nlm.nih.gov/refseq/MANE/

So from my reading, it sounds like the canonical transcript should be the MANE select (can be used for ENST and Refseq) and then if not there, default to the Refseq select.

**Comment by davmlaw** [comment]
File is here:

https://ftp.ncbi.nlm.nih.gov/refseq/MANE/MANE_human/current/

Filename keeps changing with each release

**Comment by davmlaw** [comment]
Once we have a way of knowing canonical transcripts for genes, we could allow searching by technically invalid HGVS like "GATA2(NM_032638.5):c.1082G>C"

This is half implemented in ```HGVSMatcher.fix_swapped_gene_transcript``` - just needs canonical transcript.

**Comment by davmlaw** [comment]
VEP --mane option has been [fixed for RefSeq since v104](https://github.com/Ensembl/ensembl-vep/issues/955) which means we could just add 2 bools to variant/transcript annotation and read in  MANE_SELECT and MANE_PLUS_CLINICAL - however since MANE is per-gene it seems much more efficient to store it only once per gene

**Comment by davmlaw** [comment]
"tag" is now in cdot  0.2.12

I added TranscriptVersion.tags which is shown on the view_gene page

TODO:

* Also show on transcript version page? And variant/classification transcript select
* Build out canonical transcript (be able to get in various ways)
* Need to do manual migration to get people to upgrade cdot
* Integrate in various places that need canonical transcripts

**Comment by davmlaw** [comment]
Upgrade / deploy - Shariant test will need to upgrade to cdot data > 0.2.12 - so that RefSeq select/mane etc show

**Testing**

Previously for transcript select, we used the "representative transcript" picked by VEP. Now we use the MANE canonical (or failing that, RefSeq select)

https://test.shariant.org.au/classification/create_for_variant/8551/GRCh37 - this used to pick NM_007300.4	

So what should happen is that it should show MANE select tags on the transcript version, and default to that one

For gene pages, I have re-enabled the hotspot graphs in shariant test

This should again use MANE where available, but you can also select whatever one you want by expanding the hotspot toggle

If the hotspot graph is now good enough we can remove from shariant.py settings that disables

```VIEW_GENE_HOTSPOT_GRAPH_CLASSIFICATIONS```

**Comment by EmmaTudini** [comment]
Moving this to review QA column

**Comment by davmlaw** [comment]
Testing on test.variantgrid.com:

* The transcript tags "MANE" / "Ensembl canonical" etc appear on eg http://test.variantgrid.com/variantopedia/view_variant/2403917 but don't appear on BRCA1 - this is because it seems to have changed between the VEP version and latest Ensembl download
* can't test Hotspot graphs as they don't work with Ensembl - raised issue to use MANE transcripts there - see #745

**Comment by EmmaTudini** [comment]
@davmlaw It still looks like Shariant test hotspot graph for BRCA1 isn't selecting the MANE select transcript. Mane select for BRCA1 should be NM_007294.4 (see: https://www.ncbi.nlm.nih.gov/nuccore/NM_007294), not NM_007298.3 as is currently in shariant test.

Also are MANE annotations shown anywhere in Shariant? They don't appear on the view gene page (as specified above) 
![Screen Shot 2023-03-13 at 5.05.09 pm.png](https://images.zenhubusercontent.com/5b9760d2e008eb0aea5fff6c/6098a53e-f3cd-42f0-8ecf-90de0de1e401)

**Comment by davmlaw** [comment]
I need to load the updated annotations. I am doing that now and will let you know when done - should hopefully fix this issue

This was skipped as there was no message to do these upgrades due to a problem in 0062_one_off_cdot_upgrade

It looked at the version of the "cdot" JSON field - but that was not stored in very early versions, so it didn't tell the very old versions to upgrade

**Comment by davmlaw** [comment]
@EmmaTudini I have run the cdot annotation updates so MANE stuff should work now

**Comment by EmmaTudini** [comment]
@davmlaw Great! BRCA1 and 2 look right now. Quick question - is MANE select only against GRCh38 transcripts? See BRCA2 where MANE select is only against the GRCh38version https://test.shariant.org.au/genes/view_gene/675

**Comment by davmlaw** [comment]
Yes MANE is only against GRCh38. RefSeq 37 has "RefSeq select" which is the precursor to MANE I think

**Comment by EmmaTudini** [comment]
Checked - BRCA1, COL4A3, TP53
Should be NM_007294.4, NM_000091.5 and NM_000546.6 respectively

Actual output: Passed
