### ISSUE TITLE
vcf variant counts same for all samples

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#136]
http://144.6.229.160/snpdb/view_vcf/570

When vcf uploaded variant identical variant counts are displayed on the variant page. Can't see an issue with the actual data when samples loaded in analysis.

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/4ffd775d-9d46-4635-9eb0-cfb70da3918e)

**Comment by davmlaw** [comment]
Bug due to not skipping variants with no genotype call - hence same for all in VCF.

Needed to re-calculate existing data on test, which has finished so ready for testing.

Note: unrelated to this, except sample stats will not be done for it - am also reloading a VCF that died during import probably because I restarted services while it was importing

**Comment by sksmi** [comment]
Variant counts now different and within expected range. Haven't confirmed exact expected counts.
