### ISSUE TITLE
Analysis Template Versions - view read only analyses

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#163]
Now we can view read only analyses, make links to all the snapshots of analysis templates

**Comment by davmlaw** [comment]
Things to test here are:

* Normal analysis templates work
* When you click "view saved templates" - you see the historical ones. These are now links - you can view them but NOT edit them

**Comment by sksmi** [comment]
https://app.qase.io/run/VG/dashboard/25
Failed due to 403 for historical links for read-only account.

Also made me think about mods in the following scenario:

- I make a template and provide my group with R/W access (V1)
- I or someone else modify (e.g. change a pop freq filter) that template but don't press save bca I forget, or I don't actually want to keep those changes (not versioned)
- These changes are forgotten.
- I come back in 2 months (or 2 hrs) time and modify the template based on my experience with V1, thinking I'm modifying V1, but I'm actually modifying the un-versioned changes.
- I save (V2) and run my analyses, but am not aware that the interim changes have been applied and don't do a comparison between V1 & V2 bca I think I know what I've done. 

This equally applies if I'm mucking around with the current version of the template, and accidentally change too much. There's no way to then re-load the previous version. 

Suggestions:
- Unsaved changes are discarded when you leave the page or at least there's a warning as you leave.
- The link to the active version of the view saved templates takes you to an unlocked template (at the moment it takes you to a locked version). 
- There's a warning that you're viewed a modified draft, not an actual template version.

**Comment by davmlaw** [comment]
Need to deal with analysis permissions during cloning

Moved problem about working copy etc into  #188

**Comment by davmlaw** [comment]
OK, snapshots now rely on the template analysis permissions.

**Comment by sksmi** [comment]
PASS. Read-only access available. 

Re. #188 can we add a warning to the template wizard as a temp solution? 
> Warning: This template is in draft format until saved and may differ from the active template.  Changes are not removed from the draft version when you exit the page. 

Minor suggestion: 
Would it be possible for the template grid link to go to saved templates? Think its easier for users to understand, also makes more sense if you have read-only access. 

Happy to close - have noted comments above for future discussion if can't be addressed now.

**Comment by davmlaw** [comment]
Added comment to #6 - analysis templates polish - can do it then
