### ISSUE TITLE
Site messages for upgrades

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#178]
**Is your feature request related to a problem? Please describe.**
Users don't know when upgrades are going to occur or if they've occurred.

**Describe the solution you'd like**
2-3 days pre upgrade site message added saying something along the lines of - upgrade planned, may be some disruption during the upgrade.
1 week post-upgrade site message saying something like - VG has been recently upgraded, see X for details.

**Comment by davmlaw** [comment]
Hi, I think this should be a suggestion on Slack and not an issue. For instance, what has to happen for it to be done, then tested and closed?

**Comment by sksmi** [comment]
If I knew that I would be doing your job :) 

Assume you need to code it in as part of the upgrade scripts? Guess testing would be checking that the message is displayed..

**Comment by davmlaw** [comment]
What I'm saying is, this is a manual process - https://github.com/SACGF/variantgrid/wiki/Upgrading

Site messages was broken before the upgrade, which is why it wasn't run. I thought users did know there was an upgrade, by you manually notifying them?

To reduce disruption, I do the upgrades out of hours, and when logging on, I also look at NGINX to see if anyone (other than uptime robot) has any activity.

When you login, the front page says "Code last modified: 3 days ago, see changelog." 

The changelog can be improved, sure, there is an existing issue of "user visible changelog" - https://github.com/SACGF/variantgrid_com/issues/5 (not sure why this is in variantgrid_com)

**Comment by sksmi** [comment]
Yep i notified people, but only just before it was being run. Not sure what best process is here, q for meeting: 
- how long pre deploy should site messages be up? A couple of hours/days? what's the ideal notification process given most people only log in sporadically? 
 
Think my personal pref is 1) email - VG upgrade planned in the coming week ~7days notice. 2) site message 24hrs prior to upgrade - that at least lets me plan my analysis around the changes and then reminds me if I'm working with VG . In most cases unless something is urgent I'd wait for the changes to come through so I don't have to compare analysis pre & post upgrade (usually there's some changes in analysis  output which can often mean a bunch more analysis work if you're looking at somatics).  3) any post deploy message left up until I acknowledge and clear it - can be hrs - months between logins and would like to know all changes in that period.

**Comment by davmlaw** [comment]
Updated wiki page - https://github.com/SACGF/variantgrid/wiki/Upgrading

We've been pretty good at keeping the changelogs up to date (SAP hotfixes and VG new features)
