### ISSUE TITLE
Download all nodes

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#180]
Would be great to be able to download all nodes in 1 click - will save a bunch of time in testing.

**Comment by davmlaw** [comment]
Where did you expect to click, and what did you expect to get?

Eg In settings, and a zip of .csv files for each node? I can't see this being used normally - so an admin only link?

For a very large analysis - eg trio, it may take many minutes to generate this.

**Comment by sksmi** [comment]
Zip of csv in admin sounds good. Agree, can't see any other use than in testing, pretty sure that anyone who would be running these types of test cases would have admin access or could be given admin access.

**Comment by davmlaw** [comment]
To step back, after reading your test cases it appears your overall goal is to "Write code to validate the analysis node outputs" and you are trying to optimise this process, by going through non-standard code pathways.

The trouble is, it's not user testing then, it's basically unit testing with a manual + network step.

Thus it appears we could simplify things a lot by just automatically running code to validate the analysis nodes in a standard unit test?

**Comment by sksmi** [comment]
That would be ideal - just time dependent as need it by next week. Plan was to run a test for each filter node using similar approach to https://app.qase.io/case/VG/edit/81,  then run more complicated analysis workflows and test each node in essentially the same way to make sure we capture any caching issues etc.

I'm guessing that the ideal scenario is that someone else writes the unit tests so there's at least one other person who's independently verified the logic, but again it's a question of time/availability.

**Comment by davmlaw** [comment]
I can't download the .py file from Qase, probably because they do something to stop people spreading viruses etc.

>> capture any caching issues

I think this needs to be done manually. IMO the value to manual testing is making sure the whole end-to-end pathways work. Eg "create a population filter node, configure it, save and make sure the filters are applied" - this verifies the things that are hard to automatically verify, eg the right editor is loaded, the form saves, the database changes, workers jobs re-calculate things, result is displayed.

Automated testing is for thing little things, anything code validated and eg verifying bugs are fixed (like the 100% AF making it ignore)

Also - is testing using analysis templates a good idea? What if people use test data that doesn't contain data that meets an edge case you're testing?

>> other person who's independently verified the logic

That's a really good idea, as I'm likely to be influenced by the internals.

I think the easiest way would be to create a spreadsheet with a sheet per analysis node type, and a bunch of configurations in 1 column and what to test the grid for in the other? Then I just plow through that and turn them into automated tests?

**Comment by davmlaw** [comment]
See #192 - unit test analysis nodes
