### ISSUE TITLE
Error on filtering gene annotation grid

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#253]
http://144.6.229.160/genes/genes 

1) Search fails on gene: 
![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/406eaf42-d653-4d37-9da0-ca5f5a045f53)

2) Change search to contains (interested to see if an integer search actually works)
![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/d6f11756-5b68-4366-a30d-7f5e9da058aa)

Errors generated:  
#2317 FieldError: Related Field got invalid lookup: contains
#2247 Uncaught SyntaxError: Identifier 'JS_DATE_FORMAT_DETAILED' has already been declared

**Comment by sksmi** [comment]
Quick annotation grid check while I'm here (only tested GRCh38):

Errors on filtering using general search:
- gene symbol: error - integer required
- gene group IDs - character not integer e.g. 471,620 must be used in search (not 471620)
- gene symbol (duplicate column): error -integer required
- summary column - empty

OMIM quick filter - can't work out what this is actually filtering to - both OMIM & OMIM terms have null values for some records. Needs an update with new gene annotation? Does this impact the 'OMIM' quick filter in analysis?

**Comment by davmlaw** [comment]
Columns needed to go to the final field not just the ForeignKey - fixed via data migration

**Testing note:**

This also affected the filter node in an analysis (gene_symbol contains XXX caused node to error out)

gene group IDs is a plural - there can be multiple comma separated, which is why it is a string not int

Changed OMIM to "OMIM Terms" so it's clearer what we're filtering (not the ID - almost every gene has an ID even if no terms)

**Comment by sksmi** [comment]
Deployed. Not tested.
