### ISSUE TITLE
Gene symbol missing

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#301]
Quite a few gene symbols missing when c.hgvs present. Doesn't seem to be a transcript choice issue:
e.g. highlighted variant: http://144.6.229.160/variantopedia/view_variant/247251446
http://144.6.229.160/analysis/1973/ 

Freebayes issue? Don't remember seeing this on other analyses. 
![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/79897199-bc5c-4b8e-a01e-058abecb1a27)

**Comment by davmlaw** [comment]
This is because VariantAnnotation.transcript_version is set to NULL

This should have been set during variant import

```
VariantAnnotation.objects.filter(hgvs_c__isnull=False, transcript_version__isnull=True).count()                     
```

Seems to affect 250k variants, or 4% of the total that have a HGVS

The way this currently works is:

If Feature_type == "Transcript", then get "Feature" which is the transcript version, which we pull apart, and store if we have the transcript version in the DB. 

* I think there's an issue to replace this with a VEP field which has been added
* Run this in VEP and post the output so we know what's going on

**Comment by davmlaw** [comment]
@sksmi TLDR is that it's a deploy issue that probably only affects test - but will fix it everywhere just in case

**Comment by sksmi** [comment]
PASS. Quickcheck.
