### ISSUE TITLE
Filtering for truncating variants

### ISSUE THREAD

**Issue by a1618617** [SACGF/variantgrid#304]
Hi guys,

Previously you can filter for null variants eg. frameshift, stopgain (i.e tick a checkbox allow null), has this been removed?

**Comment by sksmi** [comment]
That checkbox was actually allowing null (e.g. na or missing) values through the filters. e.g. if you'd set a CADD threshold to 20, it would allow through variants with  variants with missing data, e.g. CADD = NA | CADD > 20  - because the effect node now uses OR logic by default this is no longer needed (note that advanced AND/null options can be accessed by clicking on the 'required' link).

Addition/removal of LOF variants is controlled via the IMPACT MIN selector. Most LOF variants (excluding splice) will be HIGH impact.
