### ISSUE TITLE
TagsNode - show tags in any analysis

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#308]
Make an option to show them too

Very useful for SA Path validation (eg SomaticReportable)

**Comment by davmlaw** [comment]
Need to fix bug: When you create a new tag node - it lists all of the tags as the name...

**Comment by davmlaw** [comment]
@sksmi - minor bug (see above) but deployed in SA Path environments for your use testing

**Comment by sksmi** [comment]
Thanks. Really great to have this!  

Tested in http://144.6.229.160/analysis/2003/

To test tagged 2 variants, 1 in each sample in this analysis:
- DSG4  18:28993589 C>T 	ExcludedRepeatRegion
- GAA 17:80105844 C>T 	CheckedIGV

Added all the nodes, then added another tag to the Coriell sample:
- DNAH17  17:78507445 G>A artefact 

A few minor comments:
Think there was a delay in the tags appearing in the tag grid:  /analysis/analyses_variant_tags/GRChXX
Assuming this is due to VG liftover. Have made note to include explanation in docs. 

Bug on creating new tag node: 
#2456 FieldError: Cannot resolve keyword 'tag' into field. Choices are: _parents, analysis, analysis_id, analysis_update_uuid, analysisnode_child, analysisnode_parent, analysisnode_ptr, analysisnode_ptr_id, analysisnodeallelesource, analysisvariable, appearance

Tag icon shows 4 tags not 3. Variants not displayed in tag grid. (guessing this might be solved by a force reload, but want to leave for you to make sure).
![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/6992fbac-9056-44a4-aa6d-3e0559dcd9d5)

Need some sort of save warning (similar to the all variants node) so that users are aware nodes aren't automatically updated if tags added to the analysis/database. e.g. when I added the 3rd tag after the tag nodes, the tag nodes aren't updated.

**Comment by davmlaw** [comment]
Hi I've already fixed this but not pushed/updated code yet.

I changed TagNode to use an Allele query (so global tags would come through as build independent) - however that introduces the problem that if you tag a variant w/o an allele, there's a slight lag as liftover occurs, and you can miss the newly created tag.

So, I changed the code to use variant queries for your own analysis (as tags/analysis will always be on same build) so they turn up immediately.

There's also other bugs (fixing)

* updating other nodes when adding tags was broken due to changes (see rollbar messages)
* If you are on all tags and remove a tag, it bumps node version under you. If you then click save it crashes as the node version is out of date

**Comment by sksmi** [comment]
Sounds good. I'll wait until you reassign me before I do any more this then.

**Comment by davmlaw** [comment]
OK fixes deployed. I was trying to be too clever - I wanted adding/removing nodes to be really fast but by doing some things async it meant that when the analysis asked whether a node needed to be reloaded, it didn't yet (but did, later)

**Comment by sksmi** [comment]
Passed prelim testing. Formal test case yet to be completed.
