### ISSUE TITLE
Variant Tag importer

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#316]
* Need to write an exporter from SA Path - might as well write as current export format
* Write an importer for current export format, can then move tags around systems.

Do as part of http://github.com/SACGF/variantgrid_sapath/issues/81

**Comment by davmlaw** [comment]
Almost finished.... ended up having to alter VariantTags (few things from #137) ie make analysis None etc.

Few issues:

* Needed to export GenomeBuild (so we know what build the variant coordinate strings are SHOWN in)
* node_id wasn't exported in old system

So will have to probably build a custom exporter from old prod but that's ok

Still TODO:

* Match up variant string using VariantPKLookup
* Match up analysis/node/users properly
* Use IDs or created to handle duplicates? Ie we don't want to insert something that's already there?
* Test that it works, performs liftovers etc etc if you upload variants you don't have in the system (ie grab from variantgrid.com or something)

**Comment by davmlaw** [comment]
In order to deal with tags that may not match to an analysis, I had to allow tags to not be linked to an analysis.

I added the ability to add/remove tags from the variant details page - you can only add 1 per tag/user (outside of an analysis)

**Comment by davmlaw** [comment]
Exported tags from VG2 May 27 at 17:55 - last tag was done at 2021-05-27 17:40

Used script to convert names and only take those after 2021-03-06 - which was 5,777 tags.

Imported into VG3Upgrade - http://frgeneseq02.imvs.sa.gov.au:92/upload/view_upload_pipeline/4934

Note: Keeping tags in sync will be an ongoing process - handled in SA Path #81

There are quite a few things to handle here, that I haven't done yet:

* Be able to delete the ones you uploaded via variant tags upload
* Handle duplicates (same variant/tag - maybe date?)

**Comment by sksmi** [comment]
**ISSUE**

Tested: 
PASS: 1 tag/user 
PASS: user can only delete own tags
ISSUE1: VG3.0 import of 3 tags created in VG2.0 27/5-3/6.  3/4 variants passed (details below). 1 tag wasn't imported, but it was created at 4:30pm 3/6 so I'm assuming this was after the cut-off (PASS).  1 variant isn't present in VG3.0 CA367310697 (FAIL). Is this because the tag importer doesn't create variants if they don't exist? 


Would vote against moving tags between systems unless explicitly requested. Two reasons:
- not user requirement & extra work for us, no time at the moment
- not all tagging is created equal, e.g. I would potentially consider moving clinical tags to research but definitely not the reverse. Have already had problems with people training in production and adding incorrect tags that then have to be manually reviewed and removed. Messy tagging could cause all sorts of issues. 

___________________________________________________
Tag Import testing details: 

PASS (TBC): CA148939 8:100454804 A>G (GRCh37)
June 3, 2021, 4:30 p.m SingleVariantARGene  - missing tag in VG3 (expected?)
May 3, 2021, 2:01 p.m SingleVariantARGene
April 12, 2021, 2:41 p.m  SingleVariantARGene
April 8, 2020, 9:50 p.m PopFreqTooCommon

FAIL: CA367310697  7:39991112 C>T (GRCh37) - variant didn't exist in VG3.0
June 2, 2021, 12:02 p.m Review 
une 1, 2021, 4:59 p.m  Inherited 

PASS: CA404805463 19:18272104 T>G (GRCh37)
May 27, 2021, 4:18 p.m Artefact 

PASS: CA392821382 15:64701919 A>C (GRCh37)
May 27, 2021, 12:22 p.m SingleVariantARGene 
May 27, 2021, 12:22 p.m VUS

**Comment by sksmi** [comment]
@davmlaw  any thoughts on a quick way to convert these guys (Clinvar download of Invitae LPP classifications) to something that would fit into the tag importer? Can spend a bunch more time working on the conversion, but am concerned about introducing bad coords into the db.. just want to add them with a tag "InvitaeLPP" to use as our gold classification set.. 

[https://app.zenhub.com/files/299486514/1ebef114-4506-4556-92d6-3af109214caa/download](https://app.zenhub.com/files/299486514/1ebef114-4506-4556-92d6-3af109214caa/download)

**Comment by davmlaw** [comment]
For the dates I was using ISO 8601 ie YYYY-MM-DD 

so "2021-03-06 and 2021-05-27"  is Mar 6 - 27 May you seem to have tested "27/5-3/6"

**Comment by davmlaw** [comment]
For the ClinVar stuff, could you use:

All variants -> Built in filter (ClinVar) -> FilterNode with clinvar_clinical_sources contains "Invitae" AND min_pathogenicity greater than 4?

What I should really do is maybe make classifications node also work on ClinVar and then allow you to specify labs

**Comment by sksmi** [comment]
Re. ClinVar, thx - I should've thought of that a while back! 

Re. tag import - to be fair I'm in lockdown. Dates are completely irrelevant. And in that case testing passes.

**Comment by sksmi** [comment]
Just tried the all variants - clinvar filter option -- remembered that I did do this before & we don't have enough variants - only gives me 218 which is too low for testing.

**Comment by sksmi** [comment]
Closing. Import managed else: [SAP#99](https://github.com/SACGF/variantgrid_sapath/issues/99)
