### ISSUE TITLE
Missed splice variant

### ISSUE THREAD

**Issue by a1618617** [SACGF/variantgrid#336]
Hi guys,

Unsure if this is a bug or not, but my issue is related to this analysis: https://variantgrid.com/analysis/794/

I previously tagged this variant (https://variantgrid.com/variantopedia/view_variant/176548324) in this family.
Being a splice donor variant with presumed "high impact" I thought it would appear in the filtered node, but it doesn't. 
Is this a bug or something to do with my setting? Any help would be appreciated. Thanks

![image](https://user-images.githubusercontent.com/16040469/115169381-fce4fc00-a0fc-11eb-94ac-c39a37167163.png)

**Comment by sksmi** [comment]
This is due to the effect node settings you've chosen.
![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/b14fea9b-3d14-4cd6-af2a-4cf469ce9951)

By selecting the required checkbox, you've filtered for variants with CADD score = 0 
Since CADD score is only available for missense variants you'll filter out a bunch of variants you're probably interested in (and I presume you don't want to exclude variants with a high CADD score). There's a whole heap more info on the effect node in the help docs.

My recommendation for a low-mod stringent approach is something like this: 

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/7b9ebd6e-4950-4388-b55e-4e251e0e6282)

You can always bump up the thresholds if you get too much through the filters. Note that you'll miss some interesting moderate impact indels with this filter (we've got a fix coming through for that shortly). Most of these will be artifacts/non-coding stuff, but there'll also be some important variants in there, so  in the meantime I also add this filter:
![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/0b278234-ca9a-41a1-b29b-2085e2b308e6)

In the end it looks like this: 
![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/375d7d56-a3f9-4f9f-a4ec-2b585b55211e)


If I apply this to your recessive node it comes through. https://variantgrid.com/analysis/2556/
Let me know if you guys want me to update the trio analysis template so you don't have to build it each time.

**Comment by sksmi** [comment]
Hi Thoung, am I ok to close this one?

**Comment by davmlaw** [comment]
You could also use "Allow Null" on the CADD score
