### ISSUE TITLE
More annotation fields from gnomAD gene constraint

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#361]
https://gnomad.broadinstitute.org/downloads#gene-constraint

gnomAD per-gene constraint scores, https://macarthurlab.org/2018/10/17/gnomad-v2-1/ ("Constraint" section)

Had a request to also use missense as well as pLOF - maybe send an email around and ask what people want?

**Comment by sksmi** [comment]
Would be good to change to o/e rather than pLI as it is much more robust. Add highlights based on upper confidence interval as per gnomAD. Include descriptive text: 'CI (upper) < 0.35 is the suggested threshold for Mendelian traits. pLOF is not applicable for curation of adult-onset conditions or genes with poor coverage.'

**Comment by davmlaw** [comment]
Check whether already done? Might as well do this now. 

https://gnomad.broadinstitute.org/downloads#v4-constraint

**Comment by davmlaw** [comment]
Made web resource loader use gnomADv4, also slightly changed on gene page so it looks like gnomAD page

Tested on vg test
