### ISSUE TITLE
Make Somalier admin only

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#367]
If we ever fix it, can always make it available to everyone again

**Comment by sksmi** [comment]
Still showing up in my non-admin account. 

e.g. http://frgeneseq02.imvs.sa.gov.au:92/snpdb/view_sample/20682

**Comment by davmlaw** [comment]
Forgot to update settings, should be fixed next deploy

**Comment by sksmi** [comment]
**PASS**
Confirmed this is admin-only in SAP :92. 

If it's extremely quick, would you be able to pop the "minimum of 1000 shared HET, 1000 shared HOM and relatedness cooefficient >= 0.2" - makes any future testing a lot easier (and I think it's looking much better so might be usable - with caution -  by TAU/admins if the filter is on there). Otherwise happy to shelve for now. 

Happy to close.

**Comment by sksmi** [comment]
Also to confirm, somalier is build-specific isn't it?

**Comment by davmlaw** [comment]
No, it's build independent

**Comment by davmlaw** [comment]
Yep will close, will just need to change settings if we ever work out how to deal with Somalier issues
