### ISSUE TITLE
Analytics / log analyzers - collect stats on user activity

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#369]
Tracking what actions users take would allow us to see if features are being used, what the most common workflows are etc.

For web analytics, personally I vote for something open source and/or server side - Google analytics is free but not sure about privacy concerns, they are linking users to their activities (if people are browsing with same browser as gmail for example)

James says:

Google Analytics force you to make sure all the data you send them is not identifiable. https://support.google.com/analytics/answer/6366371?hl=en - They don't use this data to fuel their advertising to the individuals - at least they say they don't.

SKS asks: 

Really difficult to work out if anyone is using VG and if performance is slow due to high traffic or bug. Can we add some sort of tracking of user active periods? e.g. # active user in past hr/day/wk.  Duration of active use?

**Comment by EmmaTudini** [comment]
Slightly different use case for Shariant - would like to see whether a lab has accessed a specific classification from the download in their system for evaluation purposes.

**Comment by davmlaw** [comment]
https://django-analytical.readthedocs.io/en/latest/

**Comment by TheMadBug** [comment]
So I had a look at most of the analytics out there, and 99% of them are tailored around learning your user's demographic, how they discovered your web page, which pages are generally popular with the purpose of increasing your website's usage.

Barely any of that applies to us. For Shariant purposes we're going after:
* Which labs look at how many different classifications/alleles (and then cross reference if those classifications are in discordances, are later curated by the labs themselves, or if the user came from links in their curation systems).
* General page engagement (this would be done by other tools)

So we run into problems where we're either trying to capture a LOT of fine grained solution that we probably don't want to pass to a 3rd party (and I'm not necessarily too keen on hosting our own service) or getting data that's too broad to be useful, and also not being able to cross reference with other data.

So instead I'm going for a fine grained solution with custom middleware (it's only about 50 lines) and will only turn it on for Shariant. We can turn it on for other environments easily if needed - it does cause one quick database write for every URL that it wants to record, though I'm pretty sure with some caching we could remove quite a lot of existing database overhead for every request.

In my dev branch I currently have this recording the first segment of the URL, the view name, view parameters as well as URL parameters. It can be configured to only records URLs if the start segment is in a defined set, and also ignores URLs that have a segment of "api" or "data tables" (will probably increase to more as I experiment).

I'm going to work on standardising a few importing view argument names so we can do metrics on those. e.g. currently most of the classification URLs have a view parameter called "record_id", if I rename it to "classification_id" it'll be much easier to look over view data and consolidate it.

**Comment by davmlaw** [comment]
I used to have a DB write on URLs but it made even a simple request take ~50ms sometimes depending on DB load (this hurts when a page has many requests)

The nginx logs are being written anyway, but are often not that useful because they don't have username. You can add this by adding a response header of "X-Username" then adding ```$sent_http_x_username``` to the log_format directive - see https://serverfault.com/a/604156

**Comment by TheMadBug** [comment]
So I have tried to put some smarts in it so it won't log anything for API calls - so basically one page loading for a user = only 1 database write even with ajax tabs etc.

nginx logs would be a good solution for a full fledged solution tracking all page usage, but for the purposes of seeing which labs look at which classifications, having access to the view names as well as the view parameters is super useful (though if we spent a while standardising URLs it would probably be okay - I'm probably the one more inconsistent on that front).

**Comment by TheMadBug** [comment]
I think the optimal solution would still be within Django, but using an in memory buffer to log views followed by a flush at certain intervals or buffer sizes.

**Comment by TheMadBug** [comment]
Metric page now lists the:
Most Viewed Alleles
Most Viewed Classifications (with the Allele listed next to it)
Most Viewed Discordance Reports (with Allele listed next to it)
Most Viewed Pages
Most Active Users
Recently Viewed Pages

Note that a classification view is whenever somebody goes to a page where there's an internal parameter of classification_id=xxx
So if a user somehow went straight to the diff history of a classification without looking at the classification form, that still counts.

The "view_name" shown is an internal view name, where we tried to be consistent but since it didn't really expose itself anywhere there's probably some names that might come off a bit confusing.

Also many views are loaded as parts of other views (e.g. many pages with tabs only load the data from the tab as needed). I've done my best to exclude those but I'm sure there's a bunch that will still come in. We can remove those as we find them.

**Comment by TheMadBug** [comment]
A few tweaks since this was first deployed to test:

If a user POSTs a page (as in fills in a form and hits save) their action will now have the word "POST" appear above all the parameters.

POSTs no longer record the parameter "csrfmiddlewaretoken" - this is a temporary authentication token and there's no value in persisting it. Though recordings in test prior to Tue 12th may still have it as that was when the code change was deployed.

For the Shariant configuration POSTs to /api/ are NOT recorded - as otherwise we'd be flooded with classification uploads which already have their own metrics. So when you edit a classification you do not see a POST, though we'll still see {"edit":true,"classification_id":34045} in the log.

So in Shariant the only real posts are changing your user settings, as well as changing a lab's settings. Neither of which I imagine is particularly common. POSTs also typically provide every parameter, not just the ones that are changing so you will see a lot of extra parameters if a user changes just one field.

**Comment by TheMadBug** [comment]
@davmlaw actually, this would be a good page to make graphs for :)

**Comment by EmmaTudini** [comment]
Testing:
- Logged in to Shariant test as non-admin assigned to VCGS Test (emmatudini@gmail.com), ClinVar (emmatudini+1@gmail.com), Petermac, RMH Unit 1, VCGS Unit 1 (all under emmatudini@hotmail.com)
- Most Viewed Alleles - Went to https://test.shariant.org.au/variantopedia/view_allele/2208 in each account. Went in 3 times with emmatudini@gmail.com
- Most Viewed Classifications (with the Allele listed next to it) - https://test.shariant.org.au/classification/classification/66783 in each account. Went in five times with emmatudini@hotmail.com
Most Viewed Discordance Reports (with Allele listed next to it) - DR_83. Went in two times with emmatudini+1@gmail.com. Also added in an extra view from emmatudini+1@hotmail.com straight to the discordance report diff page. 
Most Viewed Pages - Export page, upload page
Most Active Users - emails listed above
Recently Viewed Page - should be a combo of the pages above
- Logged in as emmatudini@gmail.com and modified https://test.shariant.org.au/classification/classification/64489 (Shared), https://test.shariant.org.au/classification/classification/59950?edit=true (not shared), withdrew https://test.shariant.org.au/classification/classification/66784?edit=true to resolve discordance 

Expected outputs:
- Going into a classification multiple times with the same account should not change the number of unique viewers. 
- Each unique account should add a count onto the classification record (e.g. 3 in total)
- Diffs - if from classification page, shoudl be associated with classification, if from allele page, to allele, if from discordance report, to discordance, etc 
- Filtering of days only shows action within that range (e.g. 1 day, etc)
- Editing a record will result in "edit:true". Withdrawing a record will register. 

Actual output: **Failed** Does not register the withdrawing of a record. To be continued....


Actual output: Passed
Note: @TheMadBug Would it be possible to add in the lab names into this view? The users are good but might be good for the future to know which labs they were associated to at a particular time.
Could this page be made exportable?

**Comment by TheMadBug** [comment]
>> Editing a record will result in "edit:true". Withdrawing a record will register**:
So as withdrawing is done via the API it's not captured here (that is already captured with the classification activity log).

>> Filtering by days doesn't work for most viewed pages and most active users
That does indeed seem to be a problem (or at the very least I think it shows the most active users within that time period, but then clicking on them shows their entire history). I'll investigate how easy it is to fix.

>> Also Catherine Luxford has six views but it doesn't load
Yeah that is weird, I'll try to work out why.

>> Would it be possible to add in the lab names into this view?
Yes, but I'll raise a separate task for that as it can be done later.

>> Could this page be made exportable?
Yes, but I'll raise a seperate task for this too as there's quite a few ways I could export this data, so need to work out what's most useful for you.

**Comment by TheMadBug** [comment]
See #3267 for the new issue, but I'll still work on the investigation/fixes for the day ranges and Catherine under this task.

**Comment by EmmaTudini** [comment]
@TheMadBug RE withdrawing - I'd thought that this would be a one stop place to look at metrics rather than needing to combine this page and the classification activity log?

**Comment by TheMadBug** [comment]
It would be nice, but so much data goes through the classification API it might be a bit of a mess.

We do send a parameter to say if we're sending data from the regular API or via the web form, so I could look at that.
I'll put investigation of this into the metrics improvements task, but I'd like to avoid doing it as part of this build as it's a bit too finicky. Though can put it in the build right after.

**Comment by TheMadBug** [comment]
Okay I fixed the big issue here which was the age selected (1, 7, 30, 60, 90 days) filtered the pages/users/counts etc correctly, but then when you drilled into a record e.g. a user, you'd only ever see the last 30 days of them regardless of anything else.
So since Catherine's actions were all over 30 days old, you'd never see them.

**Comment by EmmaTudini** [comment]
@TheMadBug catherine's is working now but in my account, you can still only see up till the 31st of March (even when filtering on 90 days)

**Comment by TheMadBug** [comment]
@EmmaTudini the confusion here is you have about 6 accounts all called Emma Tudini, the one that has data going back a lot more is your admin one - so you'll have to make sure "Include Admins" is selected and the badge count next to it is currently 999 but will most likely broken 1000+ by now.

**Comment by EmmaTudini** [comment]
@TheMadBug I was looking at the emmatudini@gmail.com non-admin account that I've been using for a while (I do all of my testing in this account so I'd be surprised if it wasn't used for a whole month between end of Feb and end of March). Is it because I've changed labs in the process maybe? It was originally against VCGS Unit 1.

**Comment by TheMadBug** [comment]
The functionality for recording page views was only in place as of 2022-02-25, so that's the earliest we could find a record.
Lab change wouldn't have mattered. 

Looking at the EventLog the first time you logged in after the functionality was in place was 31st of March, which matches what you see in metrics page.
<img width="655" alt="CleanShot 2022-04-27 at 16 18 31@2x" src="https://user-images.githubusercontent.com/2100255/165453833-0c5974fc-1350-43bf-9245-731427ba4d70.png">

**Comment by EmmaTudini** [comment]
Oh ok, forgot that it was only recording from a certain point in time

**Comment by EmmaTudini** [comment]
Re-checked filtering across all categories. Seems to be working as expected. - Passed
