### ISSUE TITLE
Peddy / Somalier for ancestry/relatedness

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#46]
Investigated [Peddy](https://github.com/brentp/peddy) and it works well - page says:

Note that [somalier](https://github.com/brentp/somalier) is a more scalable, faster, replacement for peddy that uses some of the same methods as peddy along with some new ones.

The main advantage Somalier has is that you can extract out the sites to a binary file, then rapidly re-compare them.

Ie so you could just run it once per sample, then generate for a Cohort or trio even from different VCFs - or even all samples!

**Comment by davmlaw** [comment]
If VCF is gzip (not bgzipped) - then we need to write a new one to generate index via tabix. When doing so, remember to use intersect with sites.vcf.gz when writing to shrink file size

**Comment by davmlaw** [comment]
* Store how many sites there are (against sample, make other sample thingy reference that)
* Have a minimum??
* Deal with having no sites… Skip - currently errors
* Integrate into VCF pipeline (only if somalier enabled=True)
* VCF page - link to report
* Run for Trio - link to report
* Sample page - show link to QC

**Comment by davmlaw** [comment]
@sksmi - this was fun, and should help find those duplicate samples!

Will fix any bugs against this issue, but please raise any new features against #162 Somalier v2 - thanks!

To test:

VCF page - new tabs, "Relate" and "Ancestry"
Sample page - new tab "Ancestry"

There is a list of related samples at the bottom, for instance on this page:

http://144.6.229.160/snpdb/view_sample/7853

You can see the 1.0 (duplicate) and 0.5  relations to the parents.

**Comment by sksmi** [comment]
**MINOR**

Functional Testing: **PASS**
- trio relationships accurately detected in SAP multi-sample vcf **PASS**
- unrelated samples do not list a somerlier result **PASS**
- contaminated sample (SAP 15624) shows high degree of relatedness **PASS** 

Documentation **HELP REQUIRED**
- have added a page in readthedocs with some basic info, haven't indexed yet as requires your review (I've made a few assumptions)

UX Suggestions: **MINOR**
- Text indicating no related samples, rather than removing section - confusing as a user & poss. more important than relatedness (for V2?)
- Round relatedness & hom concord values. 2 decimal points? 
- Add descriptive text somewhere above/below the table on the sample page (or tooltips?):

Somalier is used to calculate a pair-wise relatedness cooefficient (link:https://en.wikipedia.org/wiki/Coefficient_of_relationship) between all samples in the VariantGrid database. Samples with a relatedness cooefficient > x are displayed below. Check the sample QC results if a large number of unexpected samples are displayed. #I'm assuming there's some threshold applied.

Interpreting relatedness (for full details see wiki: https://en.wikipedia.org/wiki/Coefficient_of_relationship): 
1.00  = Identical twins/Clones/Duplicate sample
0.50  = Parent/Child/Full Sibling/Parent's Identical twin/Identical twin's child
0.35  = 3/4 sibling (e.g. same mother, fathers are siblings)
0.25  = Grandparent/Grandchild/Half-sibling/Uncle/Aunt/Niece/Nephew/Double-1st Cousin
<0.20 = Distant relative/Not related (see wiki) #paper uses 0.2 as a non-related cutoff, not sure how to interpret

Additional columns: #tooltip?
IBS0 -- the number of sites where one sample is hom-ref and another is hom-alt
IBS2 -- the number of sites where the samples have the same genotype
shared-hets -- the number of sites where both samples are heterozygotes
shared-hom-alts -- the number of sites where both samples are homozygous alternate

Warning: Somalier results are unreliable for Freebayes (?tumour-normal) data #this seems true from what I've seen, not sure if you concur, do you expect it to work for tumour-normal - paper indicates bed needed?

**Comment by davmlaw** [comment]
>> readthedocs

I've changed the headings to relatedness / ancestry as most people won't know what Somalier does and checked it in.

>> Somalier results are unreliable for Freebayes (?tumour-normal) data

Most Freebayes samples are mixed single sample somatic.

Tumor normal subtractions won't work as the common germline data is gone!

>> Text indicating no related samples, rather than removing section - confusing as a user & poss. more important than relatedness (for V2?)
>> Round relatedness & hom concord values. 2 decimal points?
>> Add descriptive text somewhere above/below the table on the sample page (or tooltips?):

Yep will do tomorrow

The main purpose of ancestry is for me to be able to find duplicate samples and remove them - all else is a bonus and can wait for v2...

**Comment by sksmi** [comment]
Deployed. Not tested.
