### ISSUE TITLE
Use cdot for transcript data

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#566]
I've finished the initial version of 

https://github.com/SACGF/cdot

Need to rewrite the gene / transcript annotation loader to use this

working in branch "cdot_genes"

Also need to change this doco:

https://github.com/SACGF/variantgrid/wiki/Generating-Transcript-Version-Data

**Comment by davmlaw** [comment]
The other thing we need to do is store HGNC ID as an integer permanently on the gene version - so that if it's imported before the HGNC records are created we can link them correctly

**Comment by davmlaw** [comment]
Also need to go through and set the ones that failed before - ie can't tell if it has gaps.

Perhaps we could look at whether any other transcript versions for same transcript have gaps

**Comment by davmlaw** [comment]
TODO: This comment is instructions for doing an upgrade

* Download files from cdot.cc
* Run commands with --clear-obsolete

**Comment by davmlaw** [comment]
Need to do another release of cdot to fix pyhgvs data conversion issue (cds_start/end)

**Comment by davmlaw** [comment]
![FQMgDksWYAMA92i](https://user-images.githubusercontent.com/763201/165418044-5e133297-58c2-47a6-bd0b-1b59b723b673.jpeg)

Finally did documentation too, https://github.com/SACGF/variantgrid/wiki/Generating-Transcript-Version-Data

**Comment by EmmaTudini** [comment]
Look at imports of PQ stuff in test

**Comment by EmmaTudini** [comment]
Testing:
- Logged in to Shariant test as admin assigned to Test lab 1 (emma.tudini@qimrberghofer.edu.au)
- To test this - I had a look at PQ variants to make sure that there weren't an overabundance of matching flags.
- Also looked at genome build missing flags as this is not common in Shariant prod

Examples
https://test.shariant.org.au/variantopedia/view_allele/16409
- seems to have lifted over after I ran liftover from the admin screen. Also re-validated but still no resolved GRCh37 and no flags to show that either. 
In prod - https://shariant.org.au/variantopedia/view_allele/14814 - no issues

To be continued...

**Comment by TheMadBug** [comment]
Re https://test.shariant.org.au/variantopedia/view_allele/16409
Running "Liftover" on the allele should ensure the 37 and 38 versions of the variant.
Then running "Matching: Re-Calculate c.hgvs" will generate the cached c.hgvs on the classification.

I've run the re-calculate on the classification in question and it seems happy now.

**Comment by EmmaTudini** [comment]
Testing:
- Logged in to Shariant test as admin assigned to Test lab 1 (emma.tudini@qimrberghofer.edu.au)
- Ran variant rematching on all variants in Shariant
1. Looked at PQ variants to make sure that there wasn't an overabundance of matching flags.
2. Also looked at genome build missing flags as this is not common in Shariant prod
3. Exported vcgs from prod as csv and then again from test. See if there are differences in flags.
4. Looked for any new flags created today after variant rematching

Expected output:
1. All flags on PQ variants should be expected
2. Shouldn't be many (or any) genome build missing flags. If there are, should also be in prod (assuming that the variant is in prod)
3. No differences in VCGS variant flags between prod and test. Note if there was a difference, prod was queried to determine whether the flag didn't exist ot had been closed and vice versa. 
4. Should be limited (expectation is that moving to cdot keeps things the same or better)

Actual output: 
1. Passed
2. Passed
3. **Failed** - @davmlaw to look into. Few variants that were different. See below:
From comparison of prod and test for VCGS
https://shariant.org.au/variantopedia/view_allele/13694
vs
https://test.shariant.org.au/variantopedia/view_allele/14812
In prod - Resolved to NM_001733.6 in both builds but then looking up the transcript, the version isn't stored in prod

https://shariant.org.au/variantopedia/view_allele/12925 
vs
https://test.shariant.org.au/variantopedia/view_allele/14044
- Stays as .4 across both genome builds in prod even though .4 only exists as GrCh37 in prod. In test, it upgrades to .5 in GRCh38

5. **Failed** - this may be more of an issue with flag raising so @TheMadBug to look into as a first pass
https://test.shariant.org.au/variantopedia/view_allele/17221
ClinVar variant imported a month ago and changed to .3 but flags only raised today (mismatch across builds and variant matching)
Also - https://test.shariant.org.au/variantopedia/view_allele/17267
https://test.shariant.org.au/variantopedia/view_allele/17260
https://test.shariant.org.au/variantopedia/view_allele/17254
https://test.shariant.org.au/variantopedia/view_allele/17252
https://test.shariant.org.au/variantopedia/view_allele/17249 - variant matching flag rather than transcript mismatch
https://test.shariant.org.au/variantopedia/view_allele/17231
https://test.shariant.org.au/variantopedia/view_allele/17217
https://test.shariant.org.au/variantopedia/view_allele/17205

Note: Once this is all fixed/looked into - suggest re-uploading petermac to test for a comparison to prod

**Comment by davmlaw** [comment]
There may be some transcript versions missing after this change

For instance we used to have a few from [UCSC](https://github.com/SACGF/shariant-admin/issues/131), but the trouble was we didn't have the alignment gap data for them, so they could have been giving the wrong coordinates

NM_001733.7 resolved to the same variant as NM_001733.6 in both builds

**Comment by EmmaTudini** [comment]
@davmlaw So does this mean that for this deploy, we need to re-run variant matching on the whole database? So that prod e,g, for NM_001733.6 goes to NM_001733.7 instead?

**Comment by davmlaw** [comment]
Probably the best thing to do is make a program that checks for this rather than requiring re-matching, there's an issue I will move up in priority:

https://github.com/SACGF/variantgrid/issues/651

**Comment by EmmaTudini** [comment]
Testing
- Did another comparison of Petermac data between test and prod
- No additional issues presented
