### ISSUE TITLE
Classification HTML title

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#570]
The HTML title for classification is "Variant Classification Groups" - we should change it to Shariant/VariantGrid HGVS (pathogenicity) or something nicer

**Comment by davmlaw** [comment]
This has a better title now. Will move to Shariant test to let them have their opinion on it...

**Comment by TheMadBug** [comment]
To clarify this is the title that will appear in the tab when you open a Classification Form (also if you bookmarked a single classification for some reason, look through browser history etc)

It now is in the form of:
_Site Name_ Classification _Gene Symbol_ _cHGVS_
e.g.
Shariant Classification SOS1 NM_005633.3(SOS1):c.1132A>G

@davmlaw what would you think about removing the site name? It's redundant to the favico, the majority of the users would only engage with one VG instance, I don't think any other pages use it, and space is very limited before tab names get cut off for the average user.

Otherwise I like it, gene symbol is obviously redundant to the HGVS but SOS1 instantly means more to people than NM_005633etc

**Comment by davmlaw** [comment]
Yeah, good idea I was so focused on the title I forgot about the favicon

**Comment by EmmaTudini** [comment]
Testing: 

- Went to https://test.shariant.org.au/classification/classification/33645 (NM transcript) and https://test.shariant.org.au/classification/classification/67402 (no gene symbol and ENST transcript)
Expected output: Both should follow the following Gene symbol classification  cHGVS

Actual output: **Failed** When no gene symbol imported, just shows the variant ID instead which doesn't mean a lot. Could change to just start with "classification" cHGVS in these cases?

THe potential issue with this tag generally is that it doesn't differentiate between labs that have submitted or records. So technically you could have the same bookmarks but point to different classifications. It is better than before in that respect

**Comment by TheMadBug** [comment]
As there are 5 classifications without gene symbol (and hopefully no more in future) accepting this one as is. It's definitely more useful than the previous title of "Variant Classification Groups"
