### ISSUE TITLE
Classification JSON export timing out - optimise or use paging

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#637]
At the moment, SA Path can't import anything as the export times out after 60 minutes:

* SA Path requests all of the records that have changed since its last successful update (Dec 17th)
* If there are more than 2000 modified records, Shariant sends ALL the records
* It takes a long time to read / process all of these records - so the connection times out after 60 mins at approx 13k records
* Because the connection died, the last successful update is not modified so stays at Dec 17 so the next connection will fail as well

It is probably a bad idea to allow such long connections anyway, as it makes us vunerable to a DDOS, perhaps it might be better to add [pagination](https://docs.djangoproject.com/en/4.0/topics/pagination/) to the classification export API so that it can be shorter requests?

But meanwhile looking there are a few things I noticed while looking at classification export:

**Since isn't used in big queries**

If there are more than 2k flag or classifications modified - it doesn't use the since optimization - so once you start falling behind you get even longer queries

**Sorting by variant coordinate** 

Only some file types require the data to be sorted (eg VCF) however we always sort, even for file types that don't need it (eg JSON)

This runs a query, sorts in Python then runs another query again - could optimise to do it in a queryset - see [issue 3287 Sort classification groups by genomic coordinate](https://github.com/SACGF/variantgrid_private/issues/3287)

**Variant vs Allele Queries**

Classification has “allele” now - so we could possibly optimise a lot of queries to use that instead of variant

** Iter_group_by_allele **

This is in an iterator, however the Django queryset does not use ```qs.iter()``` so it's executed all at once and put into RAM

**Comment by TheMadBug** [comment]
I have another issue to work on first, but will provide some quick notes now and come back to this within the week.

> Since isn't used in big queries
When I first introduced since I did some benchmarks and around 2k the query started to degrade performance. That's because it starts looking at flags which are hard to link in an optimised query.
Note that it will still perform a check that the records it actually exports have been modified recently (but it will retrieve all of them from the database).
It's the annoying thing of an old record can be withdrawn, and then un-withdrawn, and no modified dates on classifications have been changed.

The proper solution to this would be to keep a date on the alleles of 'last_classification_activity' and keep that synced with changes to classifications and their flags.

> Sorting by variant coordinate

Yeah, the sort isn't required for JSON, but having the data have a consistent sort does make testing of exports a lot easier, as well as sharing functionality between export formats has kept things a bit more robustt. That said I'm sure I could optimise the sort using the info in the issue you linked.

Most of the issue doesn't come from the sort, but the grouping. For the sake of "since", if 1 record in an allele changes, all of them are exported. This is for the sake of exports that group data such as the MVL, which might put a bit too much strain on the JSON export.

> Variant vs Allele Queries

Classification has “allele” now - so we could possibly optimise a lot of queries to use that instead of variant

Pretty sure I already have, though I may have missed a spot. Actually I have missed a spot specifically in how prepare_groups and iter_groups works.

> This is in an iterator, however the Django queryset does not use qs.iter() so it's executed all at once and put into RAM

So it's a bit more complicated than that. We do store fields from all the relevant VariantAlleles in memory at once to group them into data by Alleles, but then iter_group_by_allele will perform one select statement per allele to actually select the classifications.
So RAM shouldn't be overflowing, though the need for one query per allele is obviously a bit of an overhead.

---

If we had a better way to calculate when an allele was modified we could really optimise things. For example to do pagination currently, we would have to put all the data into memory and then sort, as the modified comes from a combination of "classification", "classification_modified", "allele flags", "classification flags".

As a short term hack to get SA Path back up, we could do a full JSON export from Shariant, import that into SA Path, then manually update the sync date - though hopefully we can find a less hacky solution to get things back to square.

**Comment by davmlaw** [comment]
Maybe not less hacky, but differently hacky is to change the Shariant Gunicorn worker timeout from 60 mins (only processed 13k records) to say 180 mins and then re-run the sync. Can do out of hours

But yeah a JSON export then loading it from file would work too - probably less to go wrong there, doesn't matter how long it takes

**Comment by TheMadBug** [comment]
So if I perform a full download of JSON from production, it takes 898 seconds.
Not speedy, but significantly under the 60 minute cut off.
This is without a since date, which might be adding enough overhead to break things.

So I would suggest the steps:
If it hasn't been done already, in SA Path admin, go to "Sync Destinations" and untick enabled for shariant_download.
From the SA Path command line, out of peak hours,  run
```
python3 manage.py classification_sync --destination shariant_download
```
Assuming the sync destination name is indeed "shariant_download".

This will trigger a full sync. If it completes successfully, re-enable the sync destination and it should be fine from then on.
(Recently in Shariant we've added some optimisation so when Alissa lab re-imports a file with no changes, it does not update the classification's modified dates. The old behaviour is what I suspect created too many modified records for SA Path to sync).

**Comment by TheMadBug** [comment]
I've also identified a lot of inefficiencies in the as_json method, primarily around "get_allele_info".
Adding some `select_related`s in and in my dev environment I've reduced the number of SQL calls for JSON export to 1/3rd.
Benchmarking the changes in test.

I expect this will allow production to go from taking 898 seconds to something like 600, 700 seconds.
Still far from perfect, but might be worth waiting until a Shariant prod update before doing the above step.

**Comment by TheMadBug** [comment]
The `selected_related`s in as_json reduced the overall download time of the full JSON format in test by 40%.
So I would recommend for waiting for the after next deploy to try a full sync offline.

**Comment by davmlaw** [comment]
@TheMadBug has this been deployed?

Try syncing again tonight?

**Comment by TheMadBug** [comment]
Yup (patched this in) so prod should be exporting JSON a lot faster now.
Try the sync again tonight and see how you go.

**Comment by davmlaw** [comment]
OK, started shell in screen, will sleep for 2 hours til 7pm then manually run shariant download (server is being used heavily at the moment)

Currently 23,584 classifications

**Comment by davmlaw** [comment]
Timed out after 60 minutes again....

**Comment by TheMadBug** [comment]
Okay there's something funky going on as a full JSON extract from Production takes under 10 minutes.
Maybe SA Path's IT inspecting every packet? Ensuring security by making sure nothing works?

So yeah, to get it back in sync in the short term all I can think of is to temporary hardcode the json load to grab the data from a file instead of a from the internet.

**Comment by davmlaw** [comment]
Downloaded on my desktop on health network at ~300k/second - 132.7Mb

Copied to TAU server, at /scratch/variantgrid/vms/vg3_upgrade/data/ - will do upload tonight

**Comment by TheMadBug** [comment]
Cool, just be aware this will require the shariant sync to be modified to load from a file (instead of a URL), as an import wont work.
As if there are labs that haven't been synced down to SA Path yet, the import will reject them.

And more importantly, there's a sanitisation process in shariant_download.py that goes on (excluding hidden data like owner_id from being copied).
Before the next SA Path deploy it might be worth me adding functionality to make catching up from a file much less tacky.

**Comment by TheMadBug** [comment]
Re the time taken (8.2 minutes) so yeah, still no idea why it exceeds an hour with an open connection then. Bizarre.

**Comment by davmlaw** [comment]
OK, the answer is that the data is different when you download with since=X

If I download with no since, it gives me 16494 records, none of which have data=None

If I download using ```since=1639746488.0```

The file has a record of:

```
{'id': 'peter_mac/molecular_diagnostic/2707_69836_1256', 'delete': True}
```

which fails due to having data=None

**Comment by TheMadBug** [comment]
Yeah, since will include withdrawns, which wont be included if you do a regular download.
(As since is effectively a patch, while without it it's a general here's the complete set of files that are valid).

Either way you can see how sync is subtly different to importing a file from
`shariant_download.py shariant_download_to_upload`

Which is why the hacky solution would be to replace the code
```
        response = requests.get(shariant.url('classification/api/classifications/export'),
                                auth=shariant.auth(),
                                params=params,
                                stream=False)

        last_modified = response.headers.get('Last-Modified')
```
with something like
```
response = open('/data/classifications_2022-07-19_GRCh38.json')
last_modified = now() - timedelta(days=1)
```
in shariant_download, rather than using the import functionality.

**Comment by davmlaw** [comment]
Well, I only added the data=None check because I thought it was due to corrupted JSON. Looks like it's not so I will remove it, will probably work this time. We didn't get a server side error last time, at least none appeared in slack

**Comment by davmlaw** [comment]
So - it originally failed due to Nonetype has no items() - see https://github.com/SACGF/variantgrid/issues/549

so it looks like I could change:

```
        data = record.get('data')
        data = sanitize_data(known_keys, data, source_url)
```

to 

```
if data := record.get('data'):
    data = sanitize_data(known_keys, data, source_url)
````

**Comment by TheMadBug** [comment]
Yeah, just noticed that code wouldn't be happy with missing data.
Alternatively `record.get('data') or dict()` should work fine, and I think the code is probably going to be happier with
`data:{}` than `data:null`

**Comment by davmlaw** [comment]
Now it fails for "since patches" due to not having a meta

https://rollbar.com/jimmy.andrews/VariantGrid/items/3872/?utm_campaign=occurrence_message&utm_medium=slack&utm_source=rollbar-notification

```
meta = record.get('meta', {})
lab_group_name := meta.get('lab_id')
lab_group_name.split('/')  # Null pointer
```

Should the since patches have a lab name in there? 

I did this client side only patch:

https://github.com/SACGF/variantgrid/commit/4bdf95f6ec8e3f13ba5ae3acf371cab2cc811e28

**Comment by TheMadBug** [comment]
So it should just be the delete records causing grief. The idea being that for delete's, it's just a matter of - have you imported this record before, if so delete it - if you don't know about it, ignore it all together.

I think this can be solved by moving
```
        if delete := record.get('delete'):
            data['delete'] = delete
```
up higher but also putting `return data` in that if block so it doesn't go to the trouble of seeing if it needs to create a lab only to delete a record from it.

Sorry about all this, I think I made it so import can handle just delete, but the download_to_upload code had a few more assumptions in it.

**Comment by davmlaw** [comment]
ok, started the import again.... (nobody using server)

**Comment by davmlaw** [comment]
26,478 classifications (23,584 2 days ago) - so quite a lot went in.

However client died from incomplete JSON - https://rollbar.com/jimmy.andrews/VariantGrid/items/3874/

Shariant server died after 1 hour timeout: https://rollbar.com/jimmy.andrews/VariantGrid/items/3873/

stream=False was still there in client, not sure what's going on. Perhaps we should examine whether the JSON is legit or not, or perhaps it's an error with the iterating JSON parser?

Anyway, as perhaps it will fix itself as it's inserted so many last time - perhaps kicking it off again might work, so I've done that now

**Comment by davmlaw** [comment]
A speed test on the VM shows it's extremely slow.

I've downloaded the JSON file manually, then modified the code to use that instead of the requests response. Seemed to be working etc. Though it causes a bit of load on server so I've just suspended the task. Will resume it out of hours

**Comment by davmlaw** [comment]
OK, there are now 27,854 entries so total of 4270 inserted over last few days.

Last run, there were a few hundred IntegrityError duplicate lab/record_id errors:

https://rollbar.com/jimmy.andrews/VariantGrid/items/3878/?utm_campaign=occurrence_message&utm_medium=slack&utm_source=rollbar-notification

This could possibly be because the previous import ran and then died. Let me know whether I need to do anything otherwise I guess it's fixed

**Comment by davmlaw** [comment]
The server side is fine, it was due to incredibly slow VM network download speed

I downloaded the JSON and then ran it from the file instead of across the network.

Praying that future downloads are small enough to download within an hour before connection timeout, will deal with then - but client side problem

Raised an issue to try and create a new VM with a different network driver and see if that improves things
