### ISSUE TITLE
Classification variant matching check - management command

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#651]
When we update cdot, or change variant matching, currently the only way to know what's changed is to re-match everything again, which is potentially quite destructive

It would be good to just iterate through each classification, attempt to match it again, and report any diferences

Could do as management command that spits out a CSV to start with.

**Comment by davmlaw** [comment]
Should do for Shariant prod testing w/o requiring rematching

**Comment by davmlaw** [comment]
There's a barebones implementation there at the moment in:

```
python3 manage.py classification_matching_check
```

But I think I should re-arrange it so that VariantCoordinateFromEvidence stores the used_transcript_accession returned in _get_variant_coordinates_from_evidence

Then be able to get out the used transcript from existing classifications and compare them too. This will mean we'll be able to track transcript version changes as well

**Comment by davmlaw** [comment]
@TheMadBug - let me know once you've deployed to Shariant test (or feel free to run it yourself)

Unfortunately can't just drop in the management command you also need a tiny code change

**Comment by TheMadBug** [comment]
@davmlaw just upgraded Shariant Test, running `python3 manage.py classification_matching_check` now

**Comment by TheMadBug** [comment]
It died on a classificaiton that didn't have a genome build, re-running with a try/catch to handle that.
If all goes right there shouldn't actually be any differences found in test since we've run classification re-matching since in test since then.
So will have to wait til we upgrade prod for a proper test of this.

**Comment by EmmaTudini** [comment]
What was the outcome of this?

**Comment by TheMadBug** [comment]
Good question, I've attached the output.
@davmlaw can you talk us through it?

[classification_match_diff.csv](https://github.com/SACGF/variantgrid/files/9413023/classification_match_diff.csv)

**Comment by davmlaw** [comment]
Well, looks like there are no changes - though there are some false positives which I'll fix (tonight or tomorrow) got to run now

Bugs:

old variant = ".", new variant = "." but says "gained variant match"

The test for both being empty must be wrong somehow

I also don't understand why

https://test.shariant.org.au/classification/classification/57860
https://test.shariant.org.au/classification/classification/44734

have existing transcripts of None when you can see it there and there doesn't appear to be any matching errors

**Comment by davmlaw** [comment]
Ah, transcript is fine, however it is ```chgvs_grch37_full``` that is left empty for GRCh37

Imported GRCh37  NM_001145026.1(PTPRQ):c.910+6_910+8del
Resolved GRCh37  -
Resolved GRCh38  NM_001145026.1(PTPRQ):c.910+6_910+8delGTT

However there are no errors/warnings on the classification - it just uses "imported" on the grid

```
In [12]: c._generate_c_hgvs_extra(GenomeBuild.grch37())                         
ERROR Could not convert '12:80849266 GAAC>G' (NM_001145026.1 (PTPRQ/GRCh37)) using ClinGen Allele Registry: A coding DNA reference sequence does not contain intron or 5' and 3' gene flanking sequences and can therefore not be used as a reference to describe variants in these regions
ERROR Could not convert '12:80849266 GAAC>G' (NM_001145026.2 (PTPRQ/GRCh37)) using ClinGen Allele Registry: A coding DNA reference sequence does not contain intron or 5' and 3' gene flanking sequences and can therefore not be used as a reference to describe variants in these regions
Traceback (most recent call last):
  File "/opt/variantgrid/classification/models/classification.py", line 2310, in _generate_c_hgvs_extra
    c_hgvs = hgvs_matcher.variant_to_c_hgvs_extra(variant, transcript_id)
  File "/opt/variantgrid/genes/hgvs.py", line 939, in variant_to_c_hgvs_extra
    return self._variant_to_hgvs_extra(variant, transcript_name)
  File "/opt/variantgrid/genes/hgvs.py", line 793, in _variant_to_hgvs_extra
    hgvs_name, hgvs_method = self._variant_to_hgvs(variant, transcript_name)
  File "/opt/variantgrid/genes/hgvs.py", line 890, in _variant_to_hgvs
    raise ValueError(f"Could not convert {variant} to HGVS - tried: {attempts}")
ValueError: Could not convert 12:80849266 GAAC>G to HGVS - tried: ClinGen Allele Registry: NM_001145026.1 (PTPRQ/GRCh37): A coding DNA reference sequence does not contain intron or 5' and 3' gene flanking sequences and can therefore not be used as a reference to describe variants in these regions, ClinGen Allele Registry: NM_001145026.2 (PTPRQ/GRCh37): A coding DNA reference sequence does not contain intron or 5' and 3' gene flanking sequences and can therefore not be used as a reference to describe variants in these regions

```

**Comment by davmlaw** [comment]
@TheMadBug if you want to give it another go...

**Comment by TheMadBug** [comment]
Yeah missing a 37 or a 38  c.hgvs representation no longer has a special spot in the HGVS Issues web page.
They do show up on the liftover report download from that page however.

**Comment by TheMadBug** [comment]
Ran it again, entire output of file is now
```
classification,provided_transcript,old_resolved_transcript,new_resolved_transcript,transcript_diff,old_variant,new_variant,variant_diff
/classification/classification/44734,NM_001145026.1,,NM_001145026.1,gained transcript,12:80849266 GAAC>G,12:80849266 GAAC>G,
/classification/classification/57860,NM_001145026.1,,NM_001145026.1,gained transcript,12:80849266 GAAC>G,12:80849266 GAAC>G,
```

**Comment by EmmaTudini** [comment]
Probably need a reminder as to what this means again please? I ran rematching and recalc chgvs on test_1638506459 but there was no change?

**Comment by TheMadBug** [comment]
So going to try and sum this up:

2 Classifications have cached transcript versions where the transcript version is marked as
NOT "OK for Local HGVS Resolution"

You can specifically see in https://test.shariant.org.au/genes/view_transcript/NM_001145026 that there's no valid 37 transcript version for this transcript.
If for the first classification in the file, you go to here and expand:
https://test.shariant.org.au/variantopedia/view_allele/13236
You can see there's no 37 c.hgvs

The caching of transcripts against classifications doesn't actually care if the transcript version is valid for matching or not - as the point of caching transcripts is more to speed up gene_symbol page linking of classifications via transcripts than it is for important matching.

The allele does have a 37 != 38 flag on it.

So I believe the two rows here are false positives due to these very specific circumstances.
So for now we just need to be aware that some rows that appear in the file of this tool might just be side effects from not being able to find a valid transcript in one genome build.

**Comment by EmmaTudini** [comment]
Ok will keep in mind for prod
