### ISSUE TITLE
Impact node not showing grid

### ISSUE THREAD

**Issue by PeerArts** [SACGF/variantgrid#727]
When I try to look at the impact node in this analysis (https://variantgrid.com/analysis/3775/), I get the error below. 
I tried reloading and re-starting the analysis, but the error keeps coming back. 

<img width="1603" alt="image" src="https://user-images.githubusercontent.com/34562740/206934665-10a2b567-92ab-47a7-883e-4762d0ec927d.png">

**Comment by davmlaw** [comment]
thanks for reporting, will try and patch tonight

**Comment by davmlaw** [comment]
This is due to gnomad_oe_lof being NaN which can't be represented in JSON

This was identified and the data was fixed in a data migration in genes/migrations/0020_auto_20210205_1043.py

However it looks like the gnomad constraint import code wasn't fixed at the same time

We need to do a data migration to fix this and the GeneAnnotation as well as fix the import

**Comment by davmlaw** [comment]
@PeerArts this should be fixed in variantgrid.com now

**Comment by PeerArts** [comment]
Yep, I can see the grid. Thanks for fixing!
