### ISSUE TITLE
Search HGVS with gene not transcript

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#731]
I thought this worked, but seems not anymore

View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/3568/](https://rollbar.com/jimmy.andrews/VariantGrid/items/3568/)

```
HGVS: Could not parse: 'HGVSName('BRCA1:c.4357+6T>C')' c.HGVS requires a transcript
```

**Comment by davmlaw** [comment]
Once we have a way of knowing canonical transcripts for genes, we could allow searching by HGVS like "GATA2:c.1082G>C"

This is half implemented in ```HGVSMatcher.fix_swapped_gene_transcript``` - just needs canonical transcript.

**Comment by davmlaw** [comment]
" nm_007294.3(BRCA1):c.5153-26A>G " also fails (due to case sensitive transcript)

**Comment by davmlaw** [comment]
This was covered in https://github.com/SACGF/variantgrid_private/issues/3415

Searching for above cases now works in Shariant test

**Comment by EmmaTudini** [comment]
@davmlaw I think SACGF/variantgrid_private#3415 only covers case insensitive searching, not gene only (no transcript) searching.

**Comment by davmlaw** [comment]
While working on the case insensitivity fix in SACGF/variantgrid_private#3415, I also re-arrange the HGVS search code, and fixed a bug that was stopping the BRCA2:c.316+5G>A search for working

**Comment by EmmaTudini** [comment]
Testing:
- Logged in as non-admin assigned to VCGS Unit 1 (tester login)
- Searched for 
1. DMD:c.434G>A
2. BRCA1:c.1A>G
3. NLRP3:c.404delG
4. CHEK2:c.1100delC
5. OTOA:c.289_300del - should generate two results - One against NM_144672.4 and one against NM_001161683.2
6. BRCA1:c.5578C>A - hasn't been matched. 
7. SLC46A1:c.512T>A - missing genome build 38 as ENST transcript couldn't be resolved, but it did lift over
8. C1R:c.1202G>A - missing genome build 37, couldn't be lifted over

Expected output: Should return page with search options that match in a timely manner.

Actual output: **Not sure** based on time to load (see times below). I think it's taking too long to deploy this change to prod. The following pass/fails will not take into account time to generate a result, but the time will be noted. 
1. **Failed** Also following was returned, see message at the top re 60 matches but only displaying 50. I think it only displayed two?
![Screen Shot 2023-04-02 at 6.52.40 pm.png](https://images.zenhubusercontent.com/5b9760d2e008eb0aea5fff6c/ecfd4290-dd8c-4f52-bfb0-1f702b413870)

Time to load result - Took 55 seconds to load search results. That's too long. It is much quicker to just search for the gene and find the variant manually. Think the load time needs optimising before going to production. 

2. Passed - generated two results - one in GRCh37 and one in GRCh38. 
Time to load: 35 seconds

3. Passed. Time to load: 20 seconds 

4. Passed - generated 4 results (which was correct), but the top result wasn't the MANE transcript (see general comments below). Time to load: 29 seconds

5. Passed - 2 results - two in GRCh38 and two in GRCh37. Time to load - 14 seconds

6. Passed (with comments) - only in GRCh37 and for a duplication rather than a SNV (see screenshot below). Not sure if this should be allowed? Any thoughts? From an initial look, it's a bit of a confusing result, so if we do allow this, it might be good to re-format the result text.
![Screen Shot 2023-04-03 at 9.55.29 am.png](https://images.zenhubusercontent.com/5b9760d2e008eb0aea5fff6c/089e1abd-ffe4-4234-997f-b5c5cfc5bc6d)

7. Passed - Two results - one in both genome builds. Good that it generated it in both builds.

8. **Failed** - went to PMID page
![Screen Shot 2023-04-03 at 10.04.07 am.png](https://images.zenhubusercontent.com/5b9760d2e008eb0aea5fff6c/af26ee26-9616-40d5-925d-1d68102173c6)

General comments
- Need to determine what is an appropriate load time for search results. 
- I think it would be good limit the number of transcripts that are listed, it gets a bit confusing. 
- Warning could be more clear, perhaps - Warning: No transcript provided, showing results for: [list the transcripts]. 
- Order search results so that MANE or refseq select transcript is at the top. It would also be good to annotate these transcripts on the search results page
- It might also be good to list the refseq and enst transcripts on separate lines for easier reference
- Should we be showing results in both genome builds if the allele linked is the same? Might be easier if they're collapsed. Or perhaps only show the users genome build? But then how would that work for test 6? 
- The link being a genomic location might not be the easiest for a curator to look at. Are there any other options of values that could be substituted in?

**Comment by davmlaw** [comment]
![Screenshot from 2023-04-03 10-46-52](https://user-images.githubusercontent.com/763201/229390901-a2c10bba-e3d9-4c2a-9574-2af8675bca57.png)

**Comment by davmlaw** [comment]
We could add an option to search - genes resolve to MANE transcript (almost no overhead vs transcript search), or look up all of them (super slow)

So if someone searches for a gene, return the MANE result quickly and a link, then a second link saying "rerun search showing all transcripts"

**Comment by EmmaTudini** [comment]
@davmlaw I thought it would be based on the number of transcripts that needs to be sorted through rather than the length of the transcript? 

RE MANE transcript, that could be a good option. I think it probably required some additional discussion with @TheMadBug and @GracePendlebury.

There are a few other issues that I've highlighted above that aren't related to the load time too.

**Comment by TheMadBug** [comment]
I have fixed the citation search from being way too flexible (if it felt it detected a citation at the very start of the search string it would use that).
Note that you can still confuse it by searching for just "C1", which it takes as a shortcut to PMCID:PMC1, though it's drowned out by ontology search results at least.

**Comment by davmlaw** [comment]
It would be good to get this done before the Shariant upgrade, but not hold it up too much.

Are you happy with:

* Present the MANE option in GRCh38, with a warning message
* For GRCh37 - we could either do MANE as well or nothing? 
* Add a setting, then disable the general gene search as it's slow and a new feature anyway

We can then raise a new issue "Search HGVS with gene symbol 2" to decide what to do after the upgrade, ie allow slow search if user chooses etc later

**Comment by EmmaTudini** [comment]
Just trying to think about the easiest option (as there are other bits of search that need fixing). Would it be possible to just  turn it off completely for now and work on it later? 

If not, agree to roll this out in stages. Can you expand on what will happen? If you search for BRCA1:c.1A>G, would it only show a result for NM_007294.4 (I think that's the mane transcript):c.1A>G and nothing else. So if a variant exists in another transcript version or transcript, it won't be shown?

Warning is definitely needed both for a result and if there are no results, so they are aware that there could be false negatives. I thought that GRCH37 didn't have MANE transcripts assigned?

**Comment by davmlaw** [comment]
How about this:

![Screenshot from 2023-04-13 14-01-01](https://user-images.githubusercontent.com/763201/231653892-5f631cbe-863e-4258-946e-0920b9102057.png)

I looked, and there are indeed 428 different transcript versions for BRCA1. WTF, do they pay them by the transcript!?

**Comment by EmmaTudini** [comment]
I think that works. In the results for, could you go even more specific and say "only showing results for the following transcripts". Could you remove the "clinvar" bit? Not quite sure what that means.

**Comment by davmlaw** [comment]
@EmmaTudini  The ClinVar bit is a search summary (lists ClinVar/classifications etc in search results) which is disabled in Shariant by default (and in the new screenshot below)

We already list the transcripts used - ie ```Results for: NM_007294.4 (MANE), ENST00000357654.9 (MANE)```  - I have moved this ahead of the warning about other transcripts

![Screenshot from 2023-04-13 14-56-48](https://user-images.githubusercontent.com/763201/231661875-70d7e7e7-c972-4d13-9a6a-2cf23507dabe.png)

I will get James to deploy it so you can test it out

**Comment by davmlaw** [comment]
Ok, added message if no results

**Comment by EmmaTudini** [comment]
![Screen Shot 2023-04-14 at 3.22.11 pm.png](https://images.zenhubusercontent.com/5b9760d2e008eb0aea5fff6c/3594e66b-c72c-4d66-b6f2-225871009f1b)

**Comment by TheMadBug** [comment]
I'm not able to recreate this, are you? Wondering if it was some weirdness of the server just restarting.

<img width="1158" alt="CleanShot 2023-04-14 at 15 47 14@2x" src="https://user-images.githubusercontent.com/2100255/231952373-7982010d-b74a-4e61-aed5-cc7b3dbac0a6.png">

**Comment by EmmaTudini** [comment]
I'm logged in as a non-admin tester, so maybe that

**Comment by TheMadBug** [comment]
Non admin I get cut down results, but at least well formatted, very weird.

<img width="1157" alt="CleanShot 2023-04-14 at 15 55 34@2x" src="https://user-images.githubusercontent.com/2100255/231953534-6764d310-592b-442c-a9f4-d52290f07f1d.png">

**Comment by EmmaTudini** [comment]
Sorry, I had put "no results" in as an example of how I'd like the search results to look

**Comment by EmmaTudini** [comment]
More testing:
- Searched for :
1. TTN:c.3574C>T (in Shariant against MANE)
2. TTN:c.3574A>T (wrong ref base)
3. TTN:c.3574C>G (alterative alt base)
4. TTN:c.3575C>T (variant doesn't exist)

Expected/actual output: 
1. SHould show warning and link. - Passed
Note: The GRCh37 result shows results for ENST00000360870.10 and then Warning: Used transcript version 'ENST00000360870.5'. It doesn't really make sense after saying - searching for .10, falling back to .5
See below: 
<img width="1203" alt="Screen Shot 2023-04-14 at 4 34 40 pm" src="https://user-images.githubusercontent.com/43164432/231962218-89582b36-07c1-44c9-8449-14069f31879b.png">

2. **Failed** - Same issue as #3415 where the ref isn't corrected
<img width="1231" alt="Screen Shot 2023-04-14 at 4 42 11 pm" src="https://user-images.githubusercontent.com/43164432/231963695-7235071f-e6a8-4f5f-b4f6-a359711d59ad.png">

3. Passed but too many warnings - 

<img width="1225" alt="Screen Shot 2023-04-14 at 4 42 22 pm" src="https://user-images.githubusercontent.com/43164432/231963734-f0f99b5b-8060-4394-80fc-0dbbcaa69155.png">

4. **Failed** - confusing to the user as doesn't show that there are no results for the search, just provides warnings. This is a blocker for deploy. 

Will move the non-blockers to a new issue

**Comment by EmmaTudini** [comment]
This is being turned off in Shariant for now

**Comment by EmmaTudini** [comment]
Testing
- Logged in as non-admin tester
- Searched for BRCA2:c.10076A>G

Expected output: Should go back to result similar to prod with error about not being able to search using the gene symbol. See below![Screenshot 2023-04-16 at 10.16.30 pm.png](https://images.zenhubusercontent.com/5b9760d2e008eb0aea5fff6c/9e4fb64a-ec84-42e2-a74b-109d2a8a4689)

Actual output: **Failed**
I think having text under results is confusing. If possible, I preferred the prod warning. ![Screenshot 2023-04-16 at 10.18.22 pm.png](https://images.zenhubusercontent.com/5b9760d2e008eb0aea5fff6c/48c09b5b-c7e2-4fdd-9b49-206cf0da711f)

**Comment by davmlaw** [comment]
I have put the "no results" warning in #802 - Search - top level warnings for no results

**Comment by EmmaTudini** [comment]
Covered under #3458
