### ISSUE TITLE
vg.com "report" function not working after classification 

### ISSUE THREAD

**Issue by PeerArts** [SACGF/variantgrid#819]
Hi Dave, 
When variants are classified, the "report" function under export is used to copy the information from the classification to a research report template. This currently doesn't work for vg.com. After classification of a variant, the 'report' function gives the following error 
![image](https://github.com/SACGF/variantgrid/assets/34562740/0587fb75-0d32-4b51-b846-3b5074293c3d)

It still works on diagnostic VG3

Thanks for looking into this. 
Peer

**Comment by davmlaw** [comment]
Hi Peer, I've adjusted the permission for that record so you can access it.

Looking into a general fix for the permission issue, which is caused by classification.views.classification_export_view.template_report calling

```
c.check_can_view(request.user)
```

ie Guardian permissions

while viewing the classification security is handled via:

```
ClassificationRef.check_security()
```

**Comment by davmlaw** [comment]
tested ok vg test
