### ISSUE TITLE
Improve user settings help

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#912]
https://variantgrid.readthedocs.io/en/latest/settings/user_settings.html

is basically empty.

And in variantgrid, [user settings](http://test.variantgrid.com/snpdb/settings/user) (click user icon top right) - tooltips on what the settings do would be super helpful

**Comment by davmlaw** [comment]
Deployed on http://test.variantgrid.com/snpdb/settings/user

@YasirKusay if you could test VG test and documents, and if OK close issue, thanks!

**Comment by YasirKusay** [comment]
Could you clarify what I should test for? Am I checking the tooltips? What else should I check?

**Comment by davmlaw** [comment]
When system testing, you make sure that the problems raised in the issue are fixed, and then test around it a little bit to try and catch any errors in the development process, ie for this one there were 2 items

1. Documents at https://variantgrid.readthedocs.io/en/latest/settings/user_settings.html - check it's been written, check spelling, grammar, whether something has been left out

2. Check tooltips appear, the help matches the column names (this would be easy to do during development so this is the kind of thing you look for when testing) and they make sense etc.

**Comment by YasirKusay** [comment]
Thanks, will look into it

**Comment by YasirKusay** [comment]
Below the settings Tab there are a few minor issues:

-  **Default Sort by Column**: Description in help and documentation is "Initial sort by column for analysis variant grid". Should it be **Sort values by this column when first creating a variantgrid analysis**
- **Tag colors**: Description in help and documentation is "Custom tag colors used in **analyis** and variant grids". There is a spelling mistake and "variant grid" should be one word.
- **Variant Link in Analysis Opens New Tab**: In the description, do you mean **opens up variant details in new tab** and not **opens up variant details in new window**. A few times you mention that you can open this up in a new window in this description. (This is the case for the description in the documentation and the help icon itself).
- **Import Messages**: Slightly different descriptions between the documentation and the help description.
- **Default Genome Build**: This is a nitpick, but instead of **jump if 1 result for this build**, it should be **jump to result if that is the only one for this build**

**Comment by davmlaw** [comment]
VariantGrid is the product, but it also contains grids of variants, which are uncapitalised ie "variant grids"

**Comment by davmlaw** [comment]
I have deployed changes to test, and updated [docs](https://variantgrid.readthedocs.io/en/latest/settings/user_settings.html) to be the same as the changes if you could please re-test and verify (may need to shift+reload pages to get new versions instead of cache)

**Comment by YasirKusay** [comment]
I believe that you used accidentally used the help message of **Default Sort by Column** in VG itself for the description of **column** in the documentation. The help message for **column** in VG itself appears to be correct. Also the help message/documentation description for **Default Sort by Column** are different.

**Variant Link in Analysis Opens New Tab** -  In the documentation, the description has not changed.

**Comment by davmlaw** [comment]
ah ok thanks, hopefully this is the final fix:

https://variantgrid.readthedocs.io/en/latest/settings/user_settings.html?blah

**Comment by YasirKusay** [comment]
Looking good, but just noticed that for **Import Messages** in both help message and documentation, it says the icon is located in the top left when it is actually located in the top right. You can close this issue once this is changed.
