### ISSUE TITLE
pfam update from web error

### ISSUE THREAD

**Issue by sksmi** [SACGF/variantgrid#96]
**Describe the bug**
pfam update from web error

**To Reproduce**
Steps to reproduce the behavior including URLs. e.g.
1. Go to https://variantgrid.com/annotation/
2. Click on pfam 'update from web' button
3. See error below

**Expected behavior**
pfam import

**Other**
https://variantgrid.com/annotation/
![image](https://user-images.githubusercontent.com/8601717/96964445-fdd41100-1551-11eb-9bec-f8261f8b1619.png)

**Comment by sksmi** [comment]
Pfam update failed. See https://app.qase.io/run/VG/dashboard/13.

**Comment by davmlaw** [comment]
The test case says it was test on VariantGrid, which doesn't have the fix applied yet. Can you please use test: http://144.6.229.160/annotation/

**Comment by sksmi** [comment]
Was in test environment - error provided in image attached to test case. 

I can't change the test steps when actually running the tests & URL was added when I first setup the case. Will use relative page ref from now on. e.g.  /annotation

**Comment by davmlaw** [comment]
OK, it died due to: "Connection timed out" - ie the server we're downloading data from had the problem.

It's a lot of work to make this work automatically - we can't just have a worker sleep and retry as eg if their FTP is down it'll lock up a worker for days/weeks/forever - and rescheduling to try again is also a pain.

I'm reloading it now, hopefully work around of "just keep hitting reload until it works" is ok - as these are admins

**Comment by davmlaw** [comment]
I've reloaded it and it worked this time, so please proceed from that point

**Comment by sksmi** [comment]
pfam upload passed, minor issue with panel app counts not matching - will log new issue. 

https://app.qase.io/run/VG/dashboard/13#

**Comment by sksmi** [comment]
Panel App issue raised: https://github.com/SACGF/variantgrid/issues/130
